- name: conditions
  hosts: local
  connection: local
  vars:
   Number: 5
  tasks:
  - name: creating conditions
    ansible.builtin.debug:
      msg: "Given Number is {{ Number }} is less than 10" #print this, if number is less than only
    when: Number > 10 #number is greater than 5
    
  