- name: functions
  hosts: local
  connection: local
  tasks:
   - name: default function
     ansible.builtin.debug:
      msg: "My name is:{{ name | default (' prasanna') }}"

# strings to list using function 
- name: functions
  hosts: local
  connection: local
  vars: 
   skills: java,python,mysql,mongodb #string
  tasks:
   - name: checking function
     ansible.builtin.debug:
      msg: "My skills are:{{ skills | split (',') }}"

# map to list using function 
- name: functions
  hosts: local
  connection: local
  vars: 
   tags: 
    environment: dev
    project: roboshop
    tools: ansible
  tasks:
   - name: checking function
     ansible.builtin.debug:
      msg: ":{{ tags | dict2items }}"

      
