- name: functions
  hosts: local
  connection: local
  tasks:
   - name: default function
     ansible.builtin.debug:
      msg: "My name is:{{ name | default (' prasanna') }}"

#map==dict==object all are same dt

# strings to list using function 
- name: functions
  hosts: local
  connection: local
  vars: 
   skills: java,python,mysql,mongodb #string
  tasks:
   - name: converting strings to list
     ansible.builtin.debug:
      msg: "My skills are:{{ skills | split (',') }}"

# map to list using function 
- name: functions
  hosts: local
  connection: local
  vars: 
   tags: 
    environment: dev
    project: roboshop
    tools: ansible
  tasks:
   - name: converting map to list
     ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"

# list to map
- name: functions
  hosts: local
  connection: local
  vars: 
   Listtags: 
   - key: environment
     value: dev
   - key: project
     value: roboshop
   - key: tools
     value: ansible
  tasks:
   - name: converting list to maps
     ansible.builtin.debug:
      msg: "{{ Listtags | items2dict }}"

# reading,convert into a var and save to a file in (instance) of pwd
- name: functions
  hosts: local
  connection: local
  tasks:
   - name: read yaml and converting into a variable
     ansible.builtin.set_fact:                                           #fact=variables,set_fact=creating vars
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"
      
   - name: converting  yaml into json
     ansible.builtin.debug:
       msg: "json:{{ student_yaml | to_json }}"

   - name: save json to file
     ansible.builtin.copy:
      dest: ./student-data.json
      content: "json:{{ student_yaml | to_nice_json }}"    #nice means readable to human

- name: functions
  hosts: local
  connection: local
  vars: 
   name: Prasanna Kukunuri
   gmail: sri@GMAIL.COM
  tasks:
   - name: case sensitive
     ansible.builtin.debug:
      msg: "{{ name | upper }}"
   - name: case sensitive
     ansible.builtin.debug:
       msg: "{{ gmail | lower }}"


# To check Ip address 
- name: functions
  hosts: local
  connection: local
  vars:
   ipaddress: "182.32.8.9"  #to check this depend pack has to be install #pip3.9 install netaddr
  tasks:
   - name: checking ipaddress valid or not
     ansible.builtin.debug:
       msg: "{{ ipaddress | ansible.utils.ipv4 }}"

# shell vs command modules
- name: modules
  hosts: local
  connection: local
  tasks:
   - name: checking with command modules
     ansible.builtin.command: cat /etc/passwd | grep root
     register: module_output
   - name: checking with output
     ansible.builtin.debug: 
       msg: " {{ module_output }}"