- name: functions
  hosts: local
  connection: local
  tasks:
   - name: default function
     ansible.builtin.debug:
      msg: "My name is:{{ name | default (' prasanna') }}"

- name: functions
  hosts: local
  connection: local
  vars: 
   skills: java,python,mysql,mongodb
  tasks:
   - name: checking function
     ansible.builtin.debug:
      msg: "My skills are:{{ skills | split (',') }}"

      
