- name: functions
  hosts: local
  connection: local
  tasks:
   - name: default function
     ansible.builtin.debug:
      msg: "My name is:{{ name | default (' prasanna') }}"

# strings to list using function 
- name: functions
  hosts: local
  connection: local
  vars: 
   skills: java,python,mysql,mongodb #string
  tasks:
   - name: converting strings to list
     ansible.builtin.debug:
      msg: "My skills are:{{ skills | split (',') }}"

# map to list using function 
- name: functions
  hosts: local
  connection: local
  vars: 
   tags: 
    environment: dev
    project: roboshop
    tools: ansible
  tasks:
   - name: converting map to list
     ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"

# list to map
- name: functions
  hosts: local
  connection: local
  vars: 
   Listtags: 
   - key: environment
     value: dev
   - key: project
     value: roboshop
   - key: tools
     value: ansible
  tasks:
   - name: converting list to maps
     ansible.builtin.debug:
      msg: "{{ Listtags | items2dict }}"

- name: functions
  hosts: local
  connection: local
  tasks:
   - name: read yaml and converting into a variable
     ansible.builtin.set_fact:
     fact_yaml:  "{{lookup( 'file', 'student.yaml' ) | from_yaml }}"
      
   - name: converting  yaml into json
     ansible.builtin.debug:
       msg: "json:{{ fact_yaml | to_json }}"