- name: loops
  hosts: local
  connection: local
  tasks:
  - name: installing packages
    ansible.builtin.package:
      name: "{{ items.name}}"
      state: "{{ items.state}}"
    loop:
    - { name: "mysql", state: "absent"} 
    - { name: "nginx", state: "absent"} 
    - { name: "zip", state: "absent"} 
